version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: quizvideo
      POSTGRES_PASSWORD: "9Ovz12XRXXiBaK_a7zEz-ydv-GV3fOrQ"
    volumes:
      - quizvideo_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "YFIRCKwj260I6_HUeRiTLitkilIqfVp9"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  quizvideo_data:
